// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhWd8tJ-u1LYLTm9zpcVD3-OTNlWWDYpY',
    appId: '1:909110535768:web:53bca41e9f3d2ff7360c2d',
    messagingSenderId: '909110535768',
    projectId: 'test-95f62',
    authDomain: 'test-95f62.firebaseapp.com',
    storageBucket: 'test-95f62.appspot.com',
    measurementId: 'G-Y461PPVFJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxx_G1E2eV73dWChmmdibu-KtFGt7K53U',
    appId: '1:909110535768:android:4e06963399f9d829360c2d',
    messagingSenderId: '909110535768',
    projectId: 'test-95f62',
    storageBucket: 'test-95f62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7HYT2U_hiJ-Ty-FnZBml9q8-Sbt8jLz4',
    appId: '1:909110535768:ios:6621fe0145e88948360c2d',
    messagingSenderId: '909110535768',
    projectId: 'test-95f62',
    storageBucket: 'test-95f62.appspot.com',
    iosClientId: '909110535768-fvr9ss5t2t028kr7a51v4u42eep8b5ok.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7HYT2U_hiJ-Ty-FnZBml9q8-Sbt8jLz4',
    appId: '1:909110535768:ios:6621fe0145e88948360c2d',
    messagingSenderId: '909110535768',
    projectId: 'test-95f62',
    storageBucket: 'test-95f62.appspot.com',
    iosClientId: '909110535768-fvr9ss5t2t028kr7a51v4u42eep8b5ok.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );
}
